#!/bin/bash

if ! [ $(id -u) = 0 ]; then
    echo "run this in root"
exit 1
fi

echo script begins...
sudo status ufw
sudo apt-get install ufw
sudo apt upgrade ufw
sudo systemctl enable ufw --now
sudo ufw enable
sudo ufw logging on

